#!/usr/bin/env python3
"""
ryznative — TRUE native backend for RYZ. Reuses ryzc's lexer/parser/AST and emits
C, then compiles with gcc to a standalone ELF (or a .so shared library). This brings
real native compilation to the canonical ryz-build ecosystem WITHOUT touching the
interpreter or the dialect — fully additive, all existing compatibilities preserved.

  ryznative <file.ryz>            -> ./<base>            native ELF (no interpreter)
  ryznative <file.ryz> --lib      -> ./lib<base>.so      shared library (export fn -> C ABI)
  ryznative <file.ryz> --emit-c   -> print generated C

Coverage: fn/export fn, let/mut, ints/floats/strings/bool, arithmetic + comparison +
and/or/not, if/else, while, for-in (list), return, break, continue, recursion,
fmt.println/print/sprintf, sys.argv/env/exit, list.len/push/get/range/new,
str.len/split/join/contains/replace/startswith/endswith/indexof, int()/str() casts.
"""
from __future__ import annotations
import importlib.util, importlib.machinery, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
_loader = importlib.machinery.SourceFileLoader("ryzc", os.path.join(HERE, "ryzc"))
_spec = importlib.util.spec_from_loader("ryzc", _loader)
ryzc = importlib.util.module_from_spec(_spec)
sys.modules["ryzc"] = ryzc
_loader.exec_module(ryzc)  # type: ignore

class NativeError(Exception): pass

# ─── C runtime header embedded in every generated file ───────────────────────
RUNTIME_H = r"""
/* ── RYZ runtime (inline, generated by ryznative) ── */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

/* ── RYZ list ── */
typedef struct { void **data; long long len; long long cap; } ryz_list;
static ryz_list *ryz_list_new(void) {
    ryz_list *l = malloc(sizeof(ryz_list));
    l->data = NULL; l->len = 0; l->cap = 0; return l; }
static void ryz_list_push(ryz_list *l, void *v) {
    if (l->len == l->cap) {
        l->cap = l->cap ? l->cap*2 : 8;
        l->data = realloc(l->data, l->cap * sizeof(void*)); }
    l->data[l->len++] = v; }
static void *ryz_list_get(ryz_list *l, long long i) {
    if (i < 0 || i >= l->len) return NULL; return l->data[i]; }
static ryz_list *ryz_list_range(long long a, long long b) {
    ryz_list *l = ryz_list_new();
    for (long long i = a; i < b; i++) ryz_list_push(l, (void*)i);
    return l; }

static int _ryz_qsort_cmp(const void *a, const void *b) {
    return strcmp(*(const char**)a, *(const char**)b); }
static void ryz_list_sort(ryz_list *l) {
    if(l->len>1) qsort(l->data, l->len, sizeof(void*), _ryz_qsort_cmp); }


/* ── RYZ fmt ── */
static void ryz_println(const char *s) { puts(s); }
static void ryz_print(const char *s) { fputs(s, stdout); fflush(stdout); }
static char *ryz_sprintf(const char *fmt, ...) {
    static char buf[4096];
    /* replace {} with positional %s/%lld/%f via va_list */
    char tmp[4096]; int pos = 0, bpos = 0;
    const char *p = fmt;
    va_list ap; va_start(ap, fmt);
    while (*p && bpos < 4090) {
        if (p[0]=='{' && p[1]=='}') {
            /* peek at next vararg type tag (we use a sentinel approach) */
            char *sv = va_arg(ap, char*);
            int n = snprintf(buf+bpos, 4090-bpos, "%s", sv);
            bpos += n; p += 2;
        } else { buf[bpos++] = *p++; }
    }
    buf[bpos] = 0; va_end(ap); return buf; }
/* typed sprintf helpers used by codegen */
static char _ryz_itoa_buf[64];
static const char *ryz_ll_to_str(long long v) { snprintf(_ryz_itoa_buf,64,"%lld",v); return _ryz_itoa_buf; }
static const char *ryz_dbl_to_str(double v)   { snprintf(_ryz_itoa_buf,64,"%g",v);  return _ryz_itoa_buf; }
static char *ryz_concat(const char *a, const char *b) {
    size_t la=strlen(a),lb=strlen(b); char *r=malloc(la+lb+1);
    memcpy(r,a,la); memcpy(r+la,b,lb+1); return r; }

/* ── RYZ str ── */
static long long ryz_str_len(const char *s) { return (long long)strlen(s); }
static int ryz_str_eq(const char *a, const char *b) { return strcmp(a,b)==0; }
static int ryz_str_contains(const char *s, const char *sub) { return strstr(s,sub)!=NULL; }
static int ryz_str_startswith(const char *s, const char *pre) { return strncmp(s,pre,strlen(pre))==0; }
static int ryz_str_endswith(const char *s, const char *suf) {
    size_t ls=strlen(s),lsu=strlen(suf); return ls>=lsu && strcmp(s+ls-lsu,suf)==0; }
static long long ryz_str_indexof(const char *s, const char *sub) {
    char *p=strstr(s,sub); return p ? (long long)(p-s) : -1LL; }
static ryz_list *ryz_str_split(const char *s, const char *sep) {
    ryz_list *l = ryz_list_new();
    if (!*sep) { for(;*s;s++) { char *c=malloc(2); c[0]=*s; c[1]=0; ryz_list_push(l,c); } return l; }
    char *tmp=strdup(s), *cur=tmp, *p;
    size_t sl=strlen(sep);
    while ((p=strstr(cur,sep))) { *p=0; ryz_list_push(l,strdup(cur)); cur=p+sl; }
    ryz_list_push(l,strdup(cur)); free(tmp); return l; }
static char *ryz_str_join(const char *sep, ryz_list *l) {
    if (l->len==0) return strdup("");
    size_t sl=strlen(sep), total=0;
    for(long long i=0;i<l->len;i++) total+=strlen((char*)l->data[i])+(i?sl:0);
    char *r=malloc(total+1); r[0]=0;
    for(long long i=0;i<l->len;i++){if(i)strcat(r,sep);strcat(r,(char*)l->data[i]);}
    return r; }
static char *ryz_str_replace(const char *s, const char *from, const char *to) {
    if (!*from) return strdup(s);
    size_t lf=strlen(from),lt=strlen(to); char buf[16384]; int bpos=0;
    const char *p=s;
    while(*p && bpos<16380){
        if(strncmp(p,from,lf)==0){memcpy(buf+bpos,to,lt);bpos+=lt;p+=lf;}
        else buf[bpos++]=*p++; }
    buf[bpos]=0; return strdup(buf); }

static char *ryz_str_slice(const char *s, long long start, long long end) {
    long long l = (long long)strlen(s);
    if (start < 0) start = 0;
    if (end > l) end = l;
    if (start >= end) return strdup("");
    char *r = malloc(end - start + 1);
    memcpy(r, s + start, end - start);
    r[end - start] = 0;
    return r; }

static char *ryz_str_lower(const char *s) {
    char *r = strdup(s);
    for(char *p = r; *p; p++) *p = tolower((unsigned char)*p);
    return r; }
static char *ryz_str_upper(const char *s) {
    char *r = strdup(s);
    for(char *p = r; *p; p++) *p = toupper((unsigned char)*p);
    return r; }
static char *ryz_str_strip(const char *s) {
    while(isspace((unsigned char)*s)) s++;
    if(*s == 0) return strdup("");
    const char *end = s + strlen(s) - 1;
    while(end > s && isspace((unsigned char)*end)) end--;
    size_t len = end - s + 1;
    char *r = malloc(len + 1);
    memcpy(r, s, len);
    r[len] = 0;
    return r; }

/* ── RYZ getenv ── */
static const char *ryz_getenv(const char *k) { const char *v = getenv(k); return v ? v : ""; }

/* ── RYZ listdir ── */
static ryz_list *ryz_sys_listdir(const char *path) {
    ryz_list *l = ryz_list_new(); DIR *d = opendir(path);
    if(!d) return l; struct dirent *de;
    while((de=readdir(d))) { 
        if(de->d_name[0]=='.' && (de->d_name[1]==0 || (de->d_name[1]=='.' && de->d_name[2]==0))) continue; 
        ryz_list_push(l, strdup(de->d_name)); 
    }
    closedir(d); return l; }


/* ── RYZ argv (populated in main) ── */
static ryz_list *RYZ_ARGV = NULL;
static int RYZ_ARGC = 0;
static char **RYZ_RAWARGV = NULL;

/* ── RYZ read_stdin ── */
static char *ryz_read_stdin(void) {
    char *buf=NULL; size_t sz=0,used=0; char tmp[4096]; size_t r;
    while((r=fread(tmp,1,sizeof(tmp),stdin))>0){
        buf=realloc(buf,used+r+1); memcpy(buf+used,tmp,r); used+=r; }
    if(!buf)buf=malloc(1); buf[used]=0; return buf; }
static char *ryz_read_file(const char *path){
    FILE *f=fopen(path,"r"); if(!f)return strdup("");
    fseek(f,0,SEEK_END); long sz=ftell(f); rewind(f);
    char *buf=malloc(sz+1); size_t read_bytes = fread(buf, 1, sz, f); buf[read_bytes] = 0; fclose(f); return buf; }
static char *ryz_shell(const char *cmd) {
    FILE *p = popen(cmd, "r"); if(!p) return strdup("");
    char *buf = NULL; size_t used = 0; char tmp[4096]; size_t r;
    while((r = fread(tmp, 1, sizeof(tmp), p)) > 0) {
        buf = realloc(buf, used + r + 1); memcpy(buf + used, tmp, r); used += r; }
    pclose(p);
    if(!buf) buf = malloc(1); buf[used] = 0; return buf; }
static int ryz_shell_ok(const char *cmd) {
    int rc = system(cmd); return rc == 0 ? 1 : 0; }
/* ── RYZ extra str ── */
static long long ryz_str_ord(const char *s) { return (long long)(unsigned char)s[0]; }
static char *ryz_str_repeat(const char *s, long long n) {
    size_t l = strlen(s); char *r = malloc(l * n + 1); r[0] = 0;
    for(long long i = 0; i < n; i++) { memcpy(r + i*l, s, l); } r[l*n] = 0; return r; }
static char *ryz_str_char_at(const char *s, long long i) {
    char *r = malloc(2); r[0] = s[i]; r[1] = 0; return r; }
static ryz_list *ryz_str_chars(const char *s) {
    ryz_list *l = ryz_list_new();
    for(; *s; s++) { char *c = malloc(2); c[0] = *s; c[1] = 0; ryz_list_push(l, c); }
    return l; }
static char *ryz_str_chr(long long n) {
    char *r = malloc(2); r[0] = (char)(n & 0xFF); r[1] = 0; return r; }
static ryz_list *ryz_list_concat(ryz_list *a, ryz_list *b) {
    ryz_list *r = ryz_list_new();
    for(long long i = 0; i < a->len; i++) ryz_list_push(r, a->data[i]);
    for(long long i = 0; i < b->len; i++) ryz_list_push(r, b->data[i]);
    return r; }
/* ── RYZ extra list ── */
static ryz_list *ryz_list_slice(ryz_list *l, long long start, long long end) {
    ryz_list *r = ryz_list_new();
    if (start < 0) start = l->len + start; if (end < 0) end = l->len + end;
    if (start < 0) start = 0; if (end > l->len) end = l->len;
    for(long long i = start; i < end; i++) ryz_list_push(r, l->data[i]);
    return r; }
static void ryz_list_set(ryz_list *l, long long i, void *v) {
    if (i >= 0 && i < l->len) l->data[i] = v; }
static ryz_list *ryz_list_reverse(ryz_list *l) {
    ryz_list *r = ryz_list_new();
    for(long long i = l->len-1; i >= 0; i--) ryz_list_push(r, l->data[i]);
    return r; }
static int ryz_sys_is_file(const char *path) {
    struct stat st; return stat(path, &st) == 0 && S_ISREG(st.st_mode); }
static int ryz_sys_is_dir(const char *path) {
    struct stat st; return stat(path, &st) == 0 && S_ISDIR(st.st_mode); }
static long long ryz_sys_size(const char *path) {
    struct stat st; return stat(path, &st) == 0 ? (long long)st.st_size : -1LL; }
"""

def cty(t):
    return {"f32": "double", "f64": "double", "string": "const char*", "bool": "int",
            "i8": "int", "u8": "int", "i16": "int", "u16": "int", "i32": "int", "u32": "int",
            "i64": "long long", "u64": "long long", "void": "void", None: "long long",
            "list": "ryz_list*"}.get(t, "long long")

def cesc(s): return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")

class Gen:
    def __init__(self, prog):
        self.prog = prog
        self.fns = [n for n in prog.items if isinstance(n, ryzc.FnDef)]
        self.ret = {f.name: cty(f.ret_ty) for f in self.fns}
        self._tmp = 0
        self._pre = []   # pre-statements for complex exprs

    def tmp(self):
        self._tmp += 1
        return f"_ryz_t{self._tmp}"

    def generate(self, mode):
        bodies = [self.fn(f) for f in self.fns if not (f.name == "main" and mode == "lib")]
        out = [RUNTIME_H]
        for f in self.fns:
            if f.name != "main": out.append(self.sig(f) + ";")
        out.append("")
        out += sum(([b, ""] for b in bodies), [])
        if mode == "exec" and not any(f.name == "main" for f in self.fns):
            out.append("int main(void){return 0;}")
        return "\n".join(out)

    def sig(self, f):
        if f.name == "main": return "int main(void)"
        params = ", ".join(f"{cty(t)} {n}" for (n, t) in f.params) or "void"
        vis = "" if f.exported else "static "
        return f"{vis}{cty(f.ret_ty)} {f.name}({params})"

    def fn(self, f):
        scope = {n: cty(t) for (n, t) in f.params}
        self._pre = []
        body_stmts = self.block(f.body, scope, 1)
        # main: inject argv setup
        init = ""
        if f.name == "main":
            init = ("    RYZ_ARGV = ryz_list_new();\n"
                    "    for(int _i=1;_i<RYZ_ARGC;_i++) ryz_list_push(RYZ_ARGV,(void*)RYZ_RAWARGV[_i]);\n")
        sig = "int main(void)" if f.name == "main" else self.sig(f)
        tail = "\n    return 0;" if f.name == "main" else ""
        body = init + body_stmts
        return f"{sig} {{\n{body}{tail}\n}}"

    def block(self, stmts, scope, d):
        return "\n".join(self.stmt(s, scope, d) for s in stmts)

    def stmt(self, n, scope, d):
        self._pre = []
        ind = "    " * d
        T = type(n).__name__
        if T == "Let":
            ex = self.expr(n.expr, scope)
            pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
            ct = self.typeof(n.expr, scope) if n.ty is None else cty(n.ty)
            scope[n.name] = ct
            return f"{pre}{ind}{ct} {n.name} = {ex};"
        if T == "Assign":
            if type(n.target).__name__ == "Ident":
                ex = self.expr(n.expr, scope)
                pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                op = n.op if n.op in ("=", "+=", "-=", "*=", "/=") else "="
                return f"{pre}{ind}{n.target.name} {op} {ex};"
            if type(n.target).__name__ == "Index":
                tgt = n.target
                obj = self.expr(tgt.obj, scope)
                idx = self.expr(tgt.idx, scope)
                val = self.expr(n.expr, scope)
                return f"{ind}ryz_list_push({obj}, (void*){val}); /* index-assign stub */"
            raise NativeError(f"native: unsupported assignment target {type(n.target).__name__}")
        if T == "Return":
            ex = self.expr(n.expr, scope) if n.expr else "0"
            pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
            return f"{pre}{ind}return {ex};"
        if T == "If":
            cond = self.expr(n.cond, scope)
            pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
            s = f"{pre}{ind}if ({cond}) {{\n{self.block(n.then_block, dict(scope), d+1)}\n{ind}}}"
            if n.else_block:
                s += f" else {{\n{self.block(n.else_block, dict(scope), d+1)}\n{ind}}}"
            return s
        if T == "While":
            cond = self.expr(n.cond, scope)
            pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
            return f"{pre}{ind}while ({cond}) {{\n{self.block(n.body, dict(scope), d+1)}\n{ind}}}"
        if T == "For":
            # for var in list_expr
            lst = self.expr(n.iter, scope)
            pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
            tmp = self.tmp()
            inner_scope = dict(scope)
            inner_scope[n.var] = "const char*"  # default element type
            body_c = self.block(n.body, inner_scope, d+2)
            return (f"{pre}{ind}{{\n"
                    f"    {ind}ryz_list *{tmp} = (ryz_list*)({lst});\n"
                    f"    {ind}for(long long _fi=0;_fi<{tmp}->len;_fi++){{\n"
                    f"        {ind}const char *{n.var} = (const char*){tmp}->data[_fi];\n"
                    f"{body_c}\n"
                    f"    {ind}}}\n"
                    f"{ind}}}")
        if T == "Break":    return f"{ind}break;"
        if T == "Continue": return f"{ind}continue;"
        if T == "Defer":    return f"{ind}/* defer not supported in native mode */"
        if T == "ExprStmt":
            return self.exprstmt(n.expr, scope, d)
        raise NativeError(f"native: statement '{T}' not supported yet (grows over time)")

    def exprstmt(self, e, scope, d):
        self._pre = []
        ind = "    " * d
        if type(e).__name__ == "Call" and type(e.callee).__name__ == "Attr":
            a = e.callee
            if type(a.obj).__name__ == "Ident":
                mod, fn = a.obj.name, a.name
                # fmt.println / fmt.print
                if mod == "fmt" and fn in ("println", "print"):
                    if len(e.args) == 1:
                        v = self.expr(e.args[0], scope)
                        pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                        t = self.typeof(e.args[0], scope)
                        if t == "const char*":
                            return f"{pre}{ind}ryz_{'println' if fn=='println' else 'print'}({v});"
                        elif t == "double":
                            return f"{pre}{ind}printf(\"%g{'\\\\n' if fn=='println' else ''}\", {v});"
                        else:
                            return f"{pre}{ind}printf(\"%lld{'\\\\n' if fn=='println' else ''}\", (long long){v});"
                    # multi-arg: join with spaces
                    parts = [self.expr(a, scope) for a in e.args]
                    pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                    prints = []
                    for i, (a2, p) in enumerate(zip(e.args, parts)):
                        if i: prints.append(f'fputs(" ", stdout);')
                        t = self.typeof(a2, scope)
                        if t == "const char*": prints.append(f"fputs({p}, stdout);")
                        elif t == "double": prints.append(f'printf("%g", {p});')
                        else: prints.append(f'printf("%lld", (long long){p});')
                    if fn == "println": prints.append("putchar('\\n');")
                    return pre + "\n".join(f"{ind}{s}" for s in prints)
                # sys.exit
                if mod == "sys" and fn == "exit":
                    v = self.expr(e.args[0], scope) if e.args else "0"
                    pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                    return f"{pre}{ind}exit((int){v});"
                # list.push
                if mod == "list" and fn == "push":
                    lst = self.expr(e.args[0], scope)
                    val = self.expr(e.args[1], scope)
                    pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                    return f"{pre}{ind}ryz_list_push({lst}, (void*)({val}));"
                # fmt.write_file / append_file
                if mod == "fmt" and fn in ("write_file", "append_file"):
                    path = self.expr(e.args[0], scope)
                    content = self.expr(e.args[1], scope)
                    pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
                    mode = "\"w\"" if fn == "write_file" else "\"a\""
                    return f"{pre}{ind}{{ FILE *_wf=fopen({path},{mode}); if(_wf){{fputs({content},_wf);fclose(_wf);}} }}"
        ex = self.expr(e, scope)
        pre = "".join(f"{ind}{s}\n" for s in self._pre); self._pre = []
        return f"{pre}{ind}{ex};"

    def typeof(self, e, scope):
        T = type(e).__name__
        if T == "IntLit": return "long long"
        if T == "FloatLit": return "double"
        if T == "StrLit": return "const char*"
        if T == "BoolLit": return "int"
        if T == "NilLit": return "void*"
        if T == "Ident": return scope.get(e.name, "long long")
        if T == "ListLit": return "ryz_list*"
        if T == "UnaryOp": return "int" if e.op in ("not", "!") else self.typeof(e.rhs, scope)
        if T == "BinOp":
            if e.op in ("<", ">", "<=", ">=", "==", "!=", "and", "or", "&&", "||"): return "int"
            lt, rt = self.typeof(e.lhs, scope), self.typeof(e.rhs, scope)
            if "const char*" in (lt, rt): return "const char*"  # string concat
            return "double" if "double" in (lt, rt) else "long long"
        if T == "Call":
            if type(e.callee).__name__ == "Ident":
                n = e.callee.name
                if n == "int": return "long long"
                if n == "str": return "const char*"
                if n == "float": return "double"
                if n == "len": return "long long"
                return self.ret.get(n, "long long")
            if type(e.callee).__name__ == "Attr":
                a = e.callee
                mod, fn = (a.obj.name if type(a.obj).__name__ == "Ident" else ""), a.name
                if mod == "fmt" and fn in ("sprintf", "read_file", "read_stdin", "read_line", "shell"): return "const char*"
                if mod == "fmt" and fn in ("shell_ok", "system"): return "int"
                if mod == "str" and fn in ("split", "chars"): return "ryz_list*"
                if mod == "str" and fn in ("chr",): return "const char*"
                if mod == "str" and fn in ("join", "replace", "concat", "slice", "lower", "upper", "strip", "trim", "repeat", "char_at"): return "const char*"
                if mod == "str" and fn in ("len", "indexof", "parse_int", "to_int", "ord"): return "long long"
                if mod == "str" and fn in ("contains", "startswith", "starts_with", "endswith", "ends_with", "eq"): return "int"
                if mod == "list" and fn in ("len",): return "long long"
                if mod == "list" and fn in ("new", "range", "filter", "map", "sort", "reverse", "slice", "concat"): return "ryz_list*"
                if mod == "list" and fn in ("get",): return "const char*"
                if mod == "sys" and fn in ("argv", "listdir"): return "ryz_list*"
                if mod == "sys" and fn in ("getcwd",): return "const char*"
                if mod == "sys" and fn in ("now_unix",): return "long long"
                if mod == "sys" and fn in ("is_file", "path_is_file", "is_dir", "path_is_dir"): return "int"
                if mod == "sys" and fn in ("size",): return "long long"
        if T == "Index":
            # sys.env["KEY"] -> const char* (ryz_getenv returns const char*)
            if type(e.obj).__name__ == "Attr":
                ao = e.obj
                if type(ao.obj).__name__ == "Ident" and ao.obj.name == "sys" and ao.name == "env":
                    return "const char*"
            ot = self.typeof(e.obj, scope)
            if ot == "ryz_list*": return "const char*"
        if T == "Attr":
            if type(e.obj).__name__ == "Ident" and e.obj.name == "sys" and e.name == "argv": return "ryz_list*"
        return "long long"

    def expr(self, e, scope):
        T = type(e).__name__
        if T == "IntLit": return f"{e.v}LL"
        if T == "FloatLit": return f"{e.v}"
        if T == "StrLit": return f'"{cesc(e.v)}"'
        if T == "BoolLit": return "1" if e.v else "0"
        if T == "NilLit": return "NULL"
        if T == "Ident": return e.name
        if T == "ListLit":
            tmp = self.tmp()
            self._pre.append(f"ryz_list *{tmp} = ryz_list_new();")
            for item in e.items:
                v = self.expr(item, scope)
                self._pre.append(f"ryz_list_push({tmp}, (void*)({v}));")
            return tmp
        if T == "UnaryOp":
            op = "!" if e.op == "not" else e.op
            return f"({op}{self.expr(e.rhs, scope)})"
        if T == "BinOp":
            lt = self.typeof(e.lhs, scope)
            rt = self.typeof(e.rhs, scope)
            op = {"and": "&&", "or": "||"}.get(e.op, e.op)
            lv = self.expr(e.lhs, scope)
            rv = self.expr(e.rhs, scope)
            # string equality
            if e.op in ("==", "!=") and (lt == "const char*" or rt == "const char*"):
                eq = f"ryz_str_eq({lv},{rv})"
                return f"(!{eq})" if e.op == "!=" else eq
            # string concat
            if e.op == "+" and (lt == "const char*" or rt == "const char*"):
                lv2 = lv if lt == "const char*" else f"ryz_ll_to_str({lv})"
                rv2 = rv if rt == "const char*" else f"ryz_ll_to_str({rv})"
                return f"ryz_concat({lv2},{rv2})"
            return f"({lv} {op} {rv})"
        if T == "Index":
            # sys.env["KEY"] -> ryz_getenv("KEY")
            if type(e.obj).__name__ == "Attr":
                ao = e.obj
                if type(ao.obj).__name__ == "Ident" and ao.obj.name == "sys" and ao.name == "env":
                    key = self.expr(e.idx, scope)
                    return f"ryz_getenv({key})"
            obj = self.expr(e.obj, scope)
            idx = self.expr(e.idx, scope)
            ot = self.typeof(e.obj, scope)
            if ot == "ryz_list*":
                return f"(const char*)ryz_list_get({obj},{idx})"
            return f"({obj})[{idx}]"
        if T == "Attr":
            # sys.argv as standalone expression
            if type(e.obj).__name__ == "Ident" and e.obj.name == "sys" and e.name == "argv":
                return "RYZ_ARGV"
            if type(e.obj).__name__ == "Ident" and e.obj.name == "sys" and e.name == "platform":
                return '"linux"'
            raise NativeError(f"native: bare attribute access sys.{e.name} not supported as expression (use function calls)")
        if T == "Call":
            if type(e.callee).__name__ == "Ident":
                fn = e.callee.name
                if fn == "int":
                    v = self.expr(e.args[0], scope)
                    t = self.typeof(e.args[0], scope)
                    if t == "const char*": return f"atoll({v})"
                    return f"(long long)({v})"
                if fn == "float":
                    v = self.expr(e.args[0], scope)
                    return f"(double)({v})"
                if fn == "str":
                    v = self.expr(e.args[0], scope)
                    t = self.typeof(e.args[0], scope)
                    if t == "const char*": return v
                    if t == "double": return f"ryz_dbl_to_str({v})"
                    return f"ryz_ll_to_str({v})"
                if fn == "len":
                    v = self.expr(e.args[0], scope)
                    t = self.typeof(e.args[0], scope)
                    if t == "ryz_list*": return f"((ryz_list*)({v}))->len"
                    return f"(long long)strlen({v})"
                args = ", ".join(self.expr(a, scope) for a in e.args)
                return f"{fn}({args})"
            if type(e.callee).__name__ == "Attr":
                a = e.callee
                if type(a.obj).__name__ != "Ident":
                    raise NativeError("native: chained method calls not supported yet")
                mod, fn = a.obj.name, a.name
                def aex(i): return self.expr(e.args[i], scope)
                # fmt module
                if mod == "fmt":
                    if fn in ("println", "print"):
                        # as expression (rare) — side effect only
                        if e.args:
                            v = aex(0); t = self.typeof(e.args[0], scope)
                            if t == "const char*": return f'(ryz_{"println" if fn=="println" else "print"}({v}),0)'
                            return f'(printf("%lld\\n",(long long){v}),0)'
                        return '(putchar(\'\\n\'),0)'
                    if fn == "sprintf":
                        # ryz sprintf(fmt_str, v1, v2, ...) -> string concat chain
                        if len(e.args) == 1: return aex(0)
                        # split fmt string literal on "{}" and interleave args
                        fmt_node = e.args[0]
                        if type(fmt_node).__name__ == "StrLit":
                            parts = fmt_node.v.split("{}")
                            val_args = e.args[1:]
                            # build: parts[0] + val0 + parts[1] + val1 + ...
                            pieces = []
                            for i, p in enumerate(parts):
                                if p:
                                    pieces.append(f'"{cesc(p)}"')
                                if i < len(val_args):
                                    v = self.expr(val_args[i], scope)
                                    t = self.typeof(val_args[i], scope)
                                    if t == "const char*": pieces.append(v)
                                    elif t == "double": pieces.append(f"ryz_dbl_to_str({v})")
                                    else: pieces.append(f"ryz_ll_to_str({v})")
                            if not pieces: return '""'
                            result = pieces[0]
                            for p in pieces[1:]:
                                result = f"ryz_concat({result},{p})"
                            return result
                        # fallback: single arg
                        val = aex(1); t = self.typeof(e.args[1], scope)
                        if t == "const char*": return val
                        if t == "double": return f"ryz_dbl_to_str({val})"
                        return f"ryz_ll_to_str({val})"
                    if fn == "read_stdin": return "ryz_read_stdin()"
                    if fn == "read_file": return f"ryz_read_file({aex(0)})"
                    if fn == "read_line": return '""'  # stub
                    if fn == "shell": return f"ryz_shell({aex(0)})"
                    if fn == "shell_ok": return f"ryz_shell_ok({aex(0)})"
                    if fn == "system": return f"(system({aex(0)}),0)"
                # sys module
                if mod == "sys":
                    if fn == "exit":
                        v = aex(0) if e.args else "0"
                        return f"(exit((int){v}),0)"
                    if fn == "argv": return "RYZ_ARGV"
                    if fn == "getcwd":
                        return "(getcwd(malloc(4096),4096))"
                    if fn == "path_exists":
                        return f"(access({aex(0)},F_OK)==0)"
                    if fn == "now_unix":
                        return "((long long)time(NULL))"
                    if fn == "listdir":
                        return f"ryz_sys_listdir({aex(0)})"
                    if fn == "mkdir":
                        return f"(mkdir({aex(0)}, 0755), 0)"
                    if fn == "rename":
                        return f"(rename({aex(0)}, {aex(1)}), 0)"
                    if fn == "remove":
                        return f"(unlink({aex(0)})==0 ? 0 : rmdir({aex(0)}))"
                    if fn in ("is_file", "path_is_file"):
                        return f"ryz_sys_is_file({aex(0)})"
                    if fn in ("is_dir", "path_is_dir"):
                        return f"ryz_sys_is_dir({aex(0)})"
                    if fn == "size":
                        return f"ryz_sys_size({aex(0)})"
                # list module
                if mod == "list":
                    if fn == "len": return f"((ryz_list*)({aex(0)}))->len"
                    if fn == "new": return "ryz_list_new()"
                    if fn == "push": return f"(ryz_list_push({aex(0)},(void*)({aex(1)})),{aex(0)})"
                    if fn == "get": return f"(const char*)ryz_list_get({aex(0)},{aex(1)})"
                    if fn == "range":
                        if len(e.args) == 1: return f"ryz_list_range(0LL,{aex(0)})"
                        return f"ryz_list_range({aex(0)},{aex(1)})"
                    if fn == "contains": return f"(ryz_str_contains(ryz_str_join(\"|^^\",{aex(0)}),{aex(1)}))"
                    if fn == "sort": return f"(ryz_list_sort({aex(0)}), {aex(0)})"
                    if fn == "slice": return f"ryz_list_slice({aex(0)},{aex(1)},{aex(2)})"
                    if fn == "reverse": return f"ryz_list_reverse({aex(0)})"
                    if fn == "set": return f"(ryz_list_set({aex(0)},{aex(1)},(void*)({aex(2)})),{aex(0)})"
                    if fn == "concat": return f"ryz_list_concat({aex(0)},{aex(1)})"
                # str module
                if mod == "str":
                    if fn == "len": return f"ryz_str_len({aex(0)})"
                    if fn == "split": return f"ryz_str_split({aex(0)},{aex(1)})"
                    if fn == "join": return f"ryz_str_join({aex(1)},{aex(0)})"
                    if fn == "replace": return f"ryz_str_replace({aex(0)},{aex(1)},{aex(2)})"
                    if fn == "contains": return f"ryz_str_contains({aex(0)},{aex(1)})"
                    if fn in ("startswith", "starts_with"): return f"ryz_str_startswith({aex(0)},{aex(1)})"
                    if fn in ("endswith", "ends_with"): return f"ryz_str_endswith({aex(0)},{aex(1)})"
                    if fn == "indexof": return f"ryz_str_indexof({aex(0)},{aex(1)})"
                    if fn == "lower": return f"ryz_str_lower({aex(0)})"
                    if fn == "upper": return f"ryz_str_upper({aex(0)})"
                    if fn in ("strip", "trim"): return f"ryz_str_strip({aex(0)})"
                    if fn in ("parse_int", "to_int"): return f"atoll({aex(0)})"
                    if fn == "ord": return f"ryz_str_ord({aex(0)})"
                    if fn == "chars": return f"ryz_str_chars({aex(0)})"
                    if fn == "repeat": return f"ryz_str_repeat({aex(0)},{aex(1)})"
                    if fn == "char_at": return f"ryz_str_char_at({aex(0)},{aex(1)})"
                    if fn == "chr": return f"ryz_str_chr({aex(0)})"
                    if fn == "slice": return f"ryz_str_slice({aex(0)}, {aex(1)}, {aex(2)})"
                raise NativeError(f"native: unsupported call {mod}.{fn}")
        raise NativeError(f"native: expression '{T}' not supported yet (grows over time)")

    def _pre_flush(self):
        p = list(self._pre); self._pre = []; return p


def ryz_to_c(src, mode="exec"):
    prog = ryzc.Parser(ryzc.lex(src)).parse()
    c = Gen(prog).generate(mode)
    # patch main signature to accept argc/argv for RYZ_ARGV setup
    c = c.replace("int main(void) {", "int main(int RYZ_ARGC, char **RYZ_RAWARGV) {", 1)
    # add time.h for sys.now_unix
    c = c.replace("#include <stdlib.h>", "#include <stdlib.h>\n#include <time.h>\n#include <unistd.h>\n#include <sys/stat.h>\n#include <sys/wait.h>\n#include <dirent.h>\n#include <ctype.h>", 1)
    return c

def main():
    args = sys.argv[1:]
    if not args:
        print("usage: ryznative <file.ryz> [--lib|--emit-c]", file=sys.stderr); sys.exit(2)
    f = args[0]; mode = "lib" if "--lib" in args else "exec"
    src = open(f).read()
    base = os.path.splitext(os.path.basename(f))[0]
    try:
        c = ryz_to_c(src, mode)
    except (NativeError, SyntaxError) as e:
        print(f"ryznative: {e}", file=sys.stderr); sys.exit(1)
    if "--emit-c" in args:
        print(c); return
    cfile = f"/tmp/ryznative_{base}.c"; open(cfile, "w").write(c)
    if mode == "lib":
        out = f"lib{base}.so"
        rc = subprocess.call(["gcc", "-O2", "-std=gnu11", "-shared", "-fPIC", "-o", out, cfile])
        if rc == 0: print(f"ryznative: shared library -> {out}")
    else:
        out = base
        rc = subprocess.call(["gcc", "-O2", "-std=gnu11", "-o", out, cfile])
        if rc == 0: os.chmod(out, 0o755); print(f"ryznative: native ELF -> {out}")
    sys.exit(rc)

if __name__ == "__main__":
    main()
